### ISSUE TITLE
Article Consultation

### ISSUE THREAD

**Issue by GJTlucky** [danieltamkin4/graph-compression#2]
Hello, I am very interested in your graphic compression project. Is there any literature related to this project that I can refer to? If you could provide the names or journal numbers of the relevant literature, I would greatly appreciate it.

**Comment by tzuyichen** [comment]
It's been a while since this project was active, but here's a link to a paper that we were working with:  https://www.research.ed.ac.uk/en/publications/query-preserving-graph-compression
